backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "gallery" # Used in routes, e.g., /admin/collections/gallery
    label: "Gallery" # Used in the UI
    folder: "content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Image"
        name: "image"
        required: true
        widget: "image"
      - label: "Picture Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Upload Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
      - label: "Categories"
        name: "categories"
        default: "gallery"
        required: false
        widget: "list"
  - name: "about" # Used in routes, e.g., /admin/collections/about
    label: "About us" # Used in the UI
    folder: "content/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
      - label: "Image"
        name: "image"
        required: true
        widget: "image"
      - label: "Upload Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
      - label: "Tags"
        name: "tags"
        default: "about"
        required: false
        widget: "list"
      - label: "Description"
        name: "description"
        required: false
        widget: "string"
      - label: "Keywords"
        name: "keywords"
        required: false
        widget: "string"